fragment FilmConnection on Person {
  filmConnection {
    totalCount
    edges {
      cursor
      node {
        created
        director
        edited
        episodeID
        id
        openingCrawl
        producers
        releaseDate
        title
      }
    }
    films {
      characterConnection {
        characters {
          birthYear
          created
          edited
          eyeColor
          filmConnection {
            totalCount
          }
          gender
          hairColor
          height
          homeworld {
            climates
            created
            diameter
            edited
            gravity
            id
            name
            orbitalPeriod
            population
            rotationPeriod
            surfaceWater
            terrains
          }
          id
          mass
          name
          skinColor
          starshipConnection {
            edges {
              cursor
            }
            totalCount
          }
          vehicleConnection {
            edges {
              cursor
            }
            totalCount
          }
        }
        edges {
          cursor
          node {
            birthYear
            created
            edited
            eyeColor
            gender
            hairColor
            height
            id
            mass
            name
            skinColor
          }
        }
        totalCount
      }
      created
      director
      edited
      episodeID
      id
      openingCrawl
      planetConnection {
        edges {
          cursor
          node {
            climates
            created
            diameter
            edited
            gravity
            id
            name
            orbitalPeriod
            population
            rotationPeriod
            surfaceWater
            terrains
          }
        }
        planets {
          climates
          created
          diameter
          edited
          filmConnection {
            edges {
              cursor
            }
            totalCount
          }
          gravity
          id
          name
          orbitalPeriod
          population
          residentConnection {
            edges {
              cursor
            }
            residents {
              birthYear
              created
              edited
              eyeColor
              gender
              hairColor
              height
              id
              mass
              name
              skinColor
            }
            totalCount
          }
          rotationPeriod
          surfaceWater
          terrains
        }
        totalCount
      }
      producers
      releaseDate
      speciesConnection {
        edges {
          cursor
          node {
            averageHeight
            averageLifespan
            classification
            created
            designation
            edited
            eyeColors
            hairColors
            id
            language
            name
            skinColors
          }
        }
        species {
          averageHeight
          averageLifespan
          classification
          created
          designation
          edited
          eyeColors
          filmConnection {
            edges {
              cursor
            }
            totalCount
          }
          hairColors
          id
          language
          name
          personConnection {
            edges {
              cursor
            }
            people {
              birthYear
              created
              edited
              eyeColor
              gender
              hairColor
              height
              id
              mass
              name
              skinColor
            }
            totalCount
          }
          skinColors
        }
        totalCount
      }
      starshipConnection {
        edges {
          cursor
          node {
            MGLT
            cargoCapacity
            consumables
            costInCredits
            created
            crew
            edited
            hyperdriveRating
            id
            length
            manufacturers
            maxAtmospheringSpeed
            model
            name
            passengers
            starshipClass
          }
        }
        starships {
          MGLT
          cargoCapacity
          consumables
          costInCredits
          created
          crew
          edited
          filmConnection {
            edges {
              cursor
            }
            totalCount
          }
          hyperdriveRating
          id
          length
          manufacturers
          maxAtmospheringSpeed
          model
          name
          passengers
          pilotConnection {
            edges {
              cursor
            }
            pilots {
              birthYear
              created
              edited
              eyeColor
              gender
              hairColor
              height
              id
              mass
              name
              skinColor
            }
            totalCount
          }
          starshipClass
        }
        totalCount
      }
      title
      vehicleConnection {
        edges {
          cursor
          node {
            cargoCapacity
            consumables
            costInCredits
            created
            crew
            edited
            id
            length
            manufacturers
            maxAtmospheringSpeed
            model
            name
            passengers
            vehicleClass
          }
        }
        totalCount
        vehicles {
          cargoCapacity
          consumables
          costInCredits
          created
          crew
          edited
          filmConnection {
            edges {
              cursor
            }
            totalCount
          }
          id
          length
          manufacturers
          maxAtmospheringSpeed
          model
          name
          passengers
          pilotConnection {
            edges {
              cursor
            }
            totalCount
          }
          vehicleClass
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
  }
}
